// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/mls.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';




                abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
                  RustLibApiImplPlatform({
                    required super.handler,
                    required super.wire,
                    required super.generalizedFrbRustBinding,
                    required super.portManager,
                  });

                  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_MoteurPtr => wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteurPtr;



                  @protected AnyhowException dco_decode_AnyhowException(dynamic raw);

@protected Moteur dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(dynamic raw);

@protected Moteur dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(dynamic raw);

@protected Moteur dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(dynamic raw);

@protected Moteur dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(dynamic raw);

@protected String dco_decode_String(dynamic raw);

@protected bool dco_decode_bool(dynamic raw);

@protected InstantaneDto dco_decode_box_autoadd_instantane_dto(dynamic raw);

@protected CommitDto dco_decode_commit_dto(dynamic raw);

@protected EntrantDto dco_decode_entrant_dto(dynamic raw);

@protected InstantaneDto dco_decode_instantane_dto(dynamic raw);

@protected List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw);

@protected List<MembreDto> dco_decode_list_membre_dto(dynamic raw);

@protected List<int> dco_decode_list_prim_u_32_loose(dynamic raw);

@protected Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

@protected List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

@protected Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

@protected MembreDto dco_decode_membre_dto(dynamic raw);

@protected Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

@protected int dco_decode_u_32(dynamic raw);

@protected BigInt dco_decode_u_64(dynamic raw);

@protected int dco_decode_u_8(dynamic raw);

@protected void dco_decode_unit(dynamic raw);

@protected BigInt dco_decode_usize(dynamic raw);

@protected AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

@protected Moteur sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(SseDeserializer deserializer);

@protected Moteur sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(SseDeserializer deserializer);

@protected Moteur sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(SseDeserializer deserializer);

@protected Moteur sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(SseDeserializer deserializer);

@protected String sse_decode_String(SseDeserializer deserializer);

@protected bool sse_decode_bool(SseDeserializer deserializer);

@protected InstantaneDto sse_decode_box_autoadd_instantane_dto(SseDeserializer deserializer);

@protected CommitDto sse_decode_commit_dto(SseDeserializer deserializer);

@protected EntrantDto sse_decode_entrant_dto(SseDeserializer deserializer);

@protected InstantaneDto sse_decode_instantane_dto(SseDeserializer deserializer);

@protected List<Uint8List> sse_decode_list_list_prim_u_8_strict(SseDeserializer deserializer);

@protected List<MembreDto> sse_decode_list_membre_dto(SseDeserializer deserializer);

@protected List<int> sse_decode_list_prim_u_32_loose(SseDeserializer deserializer);

@protected Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

@protected List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

@protected Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

@protected MembreDto sse_decode_membre_dto(SseDeserializer deserializer);

@protected Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

@protected int sse_decode_u_32(SseDeserializer deserializer);

@protected BigInt sse_decode_u_64(SseDeserializer deserializer);

@protected int sse_decode_u_8(SseDeserializer deserializer);

@protected void sse_decode_unit(SseDeserializer deserializer);

@protected BigInt sse_decode_usize(SseDeserializer deserializer);

@protected int sse_decode_i_32(SseDeserializer deserializer);

@protected void sse_encode_AnyhowException(AnyhowException self, SseSerializer serializer);

@protected void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(Moteur self, SseSerializer serializer);

@protected void sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(Moteur self, SseSerializer serializer);

@protected void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(Moteur self, SseSerializer serializer);

@protected void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(Moteur self, SseSerializer serializer);

@protected void sse_encode_String(String self, SseSerializer serializer);

@protected void sse_encode_bool(bool self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_instantane_dto(InstantaneDto self, SseSerializer serializer);

@protected void sse_encode_commit_dto(CommitDto self, SseSerializer serializer);

@protected void sse_encode_entrant_dto(EntrantDto self, SseSerializer serializer);

@protected void sse_encode_instantane_dto(InstantaneDto self, SseSerializer serializer);

@protected void sse_encode_list_list_prim_u_8_strict(List<Uint8List> self, SseSerializer serializer);

@protected void sse_encode_list_membre_dto(List<MembreDto> self, SseSerializer serializer);

@protected void sse_encode_list_prim_u_32_loose(List<int> self, SseSerializer serializer);

@protected void sse_encode_list_prim_u_32_strict(Uint32List self, SseSerializer serializer);

@protected void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

@protected void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer);

@protected void sse_encode_membre_dto(MembreDto self, SseSerializer serializer);

@protected void sse_encode_opt_list_prim_u_8_strict(Uint8List? self, SseSerializer serializer);

@protected void sse_encode_u_32(int self, SseSerializer serializer);

@protected void sse_encode_u_64(BigInt self, SseSerializer serializer);

@protected void sse_encode_u_8(int self, SseSerializer serializer);

@protected void sse_encode_unit(void self, SseSerializer serializer);

@protected void sse_encode_usize(BigInt self, SseSerializer serializer);

@protected void sse_encode_i_32(int self, SseSerializer serializer);
                }
                


// Section: wire_class


        class RustLibWire implements BaseWire {

            factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
              RustLibWire(lib.ffiDynamicLibrary);
        
            /// Holds the symbol lookup function.
            final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
                _lookup;
  
            /// The symbols are looked up in [dynamicLibrary].
            RustLibWire(ffi.DynamicLibrary dynamicLibrary)
                : _lookup = dynamicLibrary.lookup;

            
            void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(
              ffi.Pointer<ffi.Void> ptr,
            ) {
              return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(
                ptr,
              );
            }

            late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteurPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>('frbgen_diaspo_niger_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur');
            late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur = _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteurPtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();
            
            void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(
              ffi.Pointer<ffi.Void> ptr,
            ) {
              return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(
                ptr,
              );
            }

            late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteurPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>('frbgen_diaspo_niger_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur');
            late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur = _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteurPtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();
            
        }
        