// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/mls.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart' if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


                /// Main entrypoint of the Rust API
                class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
                  @internal
                  static final instance = RustLib._();

                  RustLib._();

                  /// Initialize flutter_rust_bridge
                  static Future<void> init({
                    RustLibApi? api,
                    BaseHandler? handler,
                    ExternalLibrary? externalLibrary,
                    bool forceSameCodegenVersion = true,
                  }) async {
                    await instance.initImpl(
                      api: api,
                      handler: handler,
                      externalLibrary: externalLibrary,
                      forceSameCodegenVersion: forceSameCodegenVersion,
                    );
                  }

                  /// Initialize flutter_rust_bridge in mock mode.
                  /// No libraries for FFI are loaded.
                  static void initMock({
                    required RustLibApi api,
                  }) {
                    instance.initMockImpl(
                      api: api,
                    );
                  }

                  /// Dispose flutter_rust_bridge
                  ///
                  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
                  /// is automatically disposed when the app stops.
                  static void dispose() => instance.disposeImpl();

                  @override
                  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor => RustLibApiImpl.new;

                  @override
                  WireConstructor<RustLibWire> get wireConstructor => RustLibWire.fromExternalLibrary;

                  @override
                  Future<void> executeRustInitializers() async {
                    
                    
                  }

                  @override
                  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig => kDefaultExternalLibraryLoaderConfig;

                  @override
                  String get codegenVersion => '2.13.0';

                  @override
                  int get rustContentHash => 1064426577;

                  static const kDefaultExternalLibraryLoaderConfig = ExternalLibraryLoaderConfig(
                    stem: 'diaspo_mls',
                    ioDirectory: 'rust/target/release/',
                    webPrefix: 'pkg/',
                    wasmBindgenName: 'wasm_bindgen',
                  );
                }
                

                abstract class RustLibApi extends BaseApi {
                  Future<CommitDto> crateApiMlsMoteurAjouterMembres({required Moteur that , required String conversationId , required List<Uint8List> keyPackages , required List<int> aad });

Future<Uint8List> crateApiMlsMoteurChiffrer({required Moteur that , required String conversationId , required List<int> clair , required List<int> aad });

Uint8List crateApiMlsMoteurCleSignaturePublique({required Moteur that });

Uint8List crateApiMlsMoteurCredential({required Moteur that });

Future<InstantaneDto> crateApiMlsMoteurCreerGroupe({required Moteur that , required String conversationId });

Future<List<Uint8List>> crateApiMlsMoteurCreerKeyPackages({required Moteur that , required int n , required bool dernierRecours });

Future<Uint8List> crateApiMlsMoteurExporterGroupInfo({required Moteur that , required String conversationId });

Future<InstantaneDto> crateApiMlsMoteurFusionnerCommitEnAttente({required Moteur that , required String conversationId });

String crateApiMlsMoteurIdentite({required Moteur that });

Future<InstantaneDto> crateApiMlsMoteurInstantane({required Moteur that , required String conversationId });

Future<void> crateApiMlsMoteurJeterCommitEnAttente({required Moteur that , required String conversationId });

Future<Moteur> crateApiMlsMoteurOuvrir({required String dbPath , required String userId , required String deviceId });

Future<CommitDto> crateApiMlsMoteurRejoindreParCommitExterne({required Moteur that , required String conversationId , required List<int> groupInfo , required List<int> aad });

Future<CommitDto> crateApiMlsMoteurRetirerMembres({required Moteur that , required String conversationId , required List<int> leafIndices , required List<int> aad });

Future<EntrantDto> crateApiMlsMoteurTraiterEntrant({required Moteur that , required String conversationId , required List<int> message , required List<int> aadAttendu });

Future<InstantaneDto> crateApiMlsMoteurTraiterWelcome({required Moteur that , required String conversationId , required List<int> welcome });

RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Moteur;

RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Moteur;

CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_MoteurPtr;


                }
                

                class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
                  RustLibApiImpl({
                    required super.handler,
                    required super.wire,
                    required super.generalizedFrbRustBinding,
                    required super.portManager,
                  });

                  @override Future<CommitDto> crateApiMlsMoteurAjouterMembres({required Moteur that , required String conversationId , required List<Uint8List> keyPackages , required List<int> aad })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(that, serializer);
sse_encode_String(conversationId, serializer);
sse_encode_list_list_prim_u_8_strict(keyPackages, serializer);
sse_encode_list_prim_u_8_loose(aad, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_commit_dto,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateApiMlsMoteurAjouterMembresConstMeta,
            argValues: [that, conversationId, keyPackages, aad],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiMlsMoteurAjouterMembresConstMeta => const TaskConstMeta(
            debugName: "Moteur_ajouter_membres",
            argNames: ["that", "conversationId", "keyPackages", "aad"],
        );
        

@override Future<Uint8List> crateApiMlsMoteurChiffrer({required Moteur that , required String conversationId , required List<int> clair , required List<int> aad })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(that, serializer);
sse_encode_String(conversationId, serializer);
sse_encode_list_prim_u_8_loose(clair, serializer);
sse_encode_list_prim_u_8_loose(aad, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateApiMlsMoteurChiffrerConstMeta,
            argValues: [that, conversationId, clair, aad],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiMlsMoteurChiffrerConstMeta => const TaskConstMeta(
            debugName: "Moteur_chiffrer",
            argNames: ["that", "conversationId", "clair", "aad"],
        );
        

@override Uint8List crateApiMlsMoteurCleSignaturePublique({required Moteur that })  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(that, serializer);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiMlsMoteurCleSignaturePubliqueConstMeta,
            argValues: [that],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiMlsMoteurCleSignaturePubliqueConstMeta => const TaskConstMeta(
            debugName: "Moteur_cle_signature_publique",
            argNames: ["that"],
        );
        

@override Uint8List crateApiMlsMoteurCredential({required Moteur that })  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(that, serializer);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateApiMlsMoteurCredentialConstMeta,
            argValues: [that],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiMlsMoteurCredentialConstMeta => const TaskConstMeta(
            debugName: "Moteur_credential",
            argNames: ["that"],
        );
        

@override Future<InstantaneDto> crateApiMlsMoteurCreerGroupe({required Moteur that , required String conversationId })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(that, serializer);
sse_encode_String(conversationId, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_instantane_dto,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateApiMlsMoteurCreerGroupeConstMeta,
            argValues: [that, conversationId],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiMlsMoteurCreerGroupeConstMeta => const TaskConstMeta(
            debugName: "Moteur_creer_groupe",
            argNames: ["that", "conversationId"],
        );
        

@override Future<List<Uint8List>> crateApiMlsMoteurCreerKeyPackages({required Moteur that , required int n , required bool dernierRecours })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(that, serializer);
sse_encode_u_32(n, serializer);
sse_encode_bool(dernierRecours, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_list_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateApiMlsMoteurCreerKeyPackagesConstMeta,
            argValues: [that, n, dernierRecours],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiMlsMoteurCreerKeyPackagesConstMeta => const TaskConstMeta(
            debugName: "Moteur_creer_key_packages",
            argNames: ["that", "n", "dernierRecours"],
        );
        

@override Future<Uint8List> crateApiMlsMoteurExporterGroupInfo({required Moteur that , required String conversationId })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(that, serializer);
sse_encode_String(conversationId, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateApiMlsMoteurExporterGroupInfoConstMeta,
            argValues: [that, conversationId],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiMlsMoteurExporterGroupInfoConstMeta => const TaskConstMeta(
            debugName: "Moteur_exporter_group_info",
            argNames: ["that", "conversationId"],
        );
        

@override Future<InstantaneDto> crateApiMlsMoteurFusionnerCommitEnAttente({required Moteur that , required String conversationId })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(that, serializer);
sse_encode_String(conversationId, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_instantane_dto,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateApiMlsMoteurFusionnerCommitEnAttenteConstMeta,
            argValues: [that, conversationId],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiMlsMoteurFusionnerCommitEnAttenteConstMeta => const TaskConstMeta(
            debugName: "Moteur_fusionner_commit_en_attente",
            argNames: ["that", "conversationId"],
        );
        

@override String crateApiMlsMoteurIdentite({required Moteur that })  { return handler.executeSync(SyncTask(
            callFfi: () {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(that, serializer);
            return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiMlsMoteurIdentiteConstMeta,
            argValues: [that],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiMlsMoteurIdentiteConstMeta => const TaskConstMeta(
            debugName: "Moteur_identite",
            argNames: ["that"],
        );
        

@override Future<InstantaneDto> crateApiMlsMoteurInstantane({required Moteur that , required String conversationId })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(that, serializer);
sse_encode_String(conversationId, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_instantane_dto,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateApiMlsMoteurInstantaneConstMeta,
            argValues: [that, conversationId],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiMlsMoteurInstantaneConstMeta => const TaskConstMeta(
            debugName: "Moteur_instantane",
            argNames: ["that", "conversationId"],
        );
        

@override Future<void> crateApiMlsMoteurJeterCommitEnAttente({required Moteur that , required String conversationId })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(that, serializer);
sse_encode_String(conversationId, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateApiMlsMoteurJeterCommitEnAttenteConstMeta,
            argValues: [that, conversationId],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiMlsMoteurJeterCommitEnAttenteConstMeta => const TaskConstMeta(
            debugName: "Moteur_jeter_commit_en_attente",
            argNames: ["that", "conversationId"],
        );
        

@override Future<Moteur> crateApiMlsMoteurOuvrir({required String dbPath , required String userId , required String deviceId })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(dbPath, serializer);
sse_encode_String(userId, serializer);
sse_encode_String(deviceId, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateApiMlsMoteurOuvrirConstMeta,
            argValues: [dbPath, userId, deviceId],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiMlsMoteurOuvrirConstMeta => const TaskConstMeta(
            debugName: "Moteur_ouvrir",
            argNames: ["dbPath", "userId", "deviceId"],
        );
        

@override Future<CommitDto> crateApiMlsMoteurRejoindreParCommitExterne({required Moteur that , required String conversationId , required List<int> groupInfo , required List<int> aad })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(that, serializer);
sse_encode_String(conversationId, serializer);
sse_encode_list_prim_u_8_loose(groupInfo, serializer);
sse_encode_list_prim_u_8_loose(aad, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_commit_dto,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateApiMlsMoteurRejoindreParCommitExterneConstMeta,
            argValues: [that, conversationId, groupInfo, aad],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiMlsMoteurRejoindreParCommitExterneConstMeta => const TaskConstMeta(
            debugName: "Moteur_rejoindre_par_commit_externe",
            argNames: ["that", "conversationId", "groupInfo", "aad"],
        );
        

@override Future<CommitDto> crateApiMlsMoteurRetirerMembres({required Moteur that , required String conversationId , required List<int> leafIndices , required List<int> aad })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(that, serializer);
sse_encode_String(conversationId, serializer);
sse_encode_list_prim_u_32_loose(leafIndices, serializer);
sse_encode_list_prim_u_8_loose(aad, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_commit_dto,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateApiMlsMoteurRetirerMembresConstMeta,
            argValues: [that, conversationId, leafIndices, aad],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiMlsMoteurRetirerMembresConstMeta => const TaskConstMeta(
            debugName: "Moteur_retirer_membres",
            argNames: ["that", "conversationId", "leafIndices", "aad"],
        );
        

@override Future<EntrantDto> crateApiMlsMoteurTraiterEntrant({required Moteur that , required String conversationId , required List<int> message , required List<int> aadAttendu })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(that, serializer);
sse_encode_String(conversationId, serializer);
sse_encode_list_prim_u_8_loose(message, serializer);
sse_encode_list_prim_u_8_loose(aadAttendu, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_entrant_dto,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateApiMlsMoteurTraiterEntrantConstMeta,
            argValues: [that, conversationId, message, aadAttendu],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiMlsMoteurTraiterEntrantConstMeta => const TaskConstMeta(
            debugName: "Moteur_traiter_entrant",
            argNames: ["that", "conversationId", "message", "aadAttendu"],
        );
        

@override Future<InstantaneDto> crateApiMlsMoteurTraiterWelcome({required Moteur that , required String conversationId , required List<int> welcome })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(that, serializer);
sse_encode_String(conversationId, serializer);
sse_encode_list_prim_u_8_loose(welcome, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_instantane_dto,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateApiMlsMoteurTraiterWelcomeConstMeta,
            argValues: [that, conversationId, welcome],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiMlsMoteurTraiterWelcomeConstMeta => const TaskConstMeta(
            debugName: "Moteur_traiter_welcome",
            argNames: ["that", "conversationId", "welcome"],
        );
        

RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Moteur => wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur;

RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Moteur => wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur;



                  @protected AnyhowException dco_decode_AnyhowException(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return AnyhowException(raw as String); }

@protected Moteur dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return MoteurImpl.frbInternalDcoDecode(raw as List<dynamic>); }

@protected Moteur dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return MoteurImpl.frbInternalDcoDecode(raw as List<dynamic>); }

@protected Moteur dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return MoteurImpl.frbInternalDcoDecode(raw as List<dynamic>); }

@protected Moteur dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return MoteurImpl.frbInternalDcoDecode(raw as List<dynamic>); }

@protected String dco_decode_String(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as String; }

@protected bool dco_decode_bool(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as bool; }

@protected InstantaneDto dco_decode_box_autoadd_instantane_dto(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return dco_decode_instantane_dto(raw); }

@protected CommitDto dco_decode_commit_dto(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 3) throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
                return CommitDto(commit: dco_decode_list_prim_u_8_strict(arr[0]),
welcome: dco_decode_opt_list_prim_u_8_strict(arr[1]),
groupInfo: dco_decode_opt_list_prim_u_8_strict(arr[2]),); }

@protected EntrantDto dco_decode_entrant_dto(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
switch (raw[0]) {
                case 0: return EntrantDto_Application(clair: dco_decode_list_prim_u_8_strict(raw[1]),);
case 1: return EntrantDto_Commit(instantane: dco_decode_box_autoadd_instantane_dto(raw[1]),);
case 2: return EntrantDto_Proposition();
case 3: return EntrantDto_Ignore();
                default: throw Exception("unreachable");
            } }

@protected InstantaneDto dco_decode_instantane_dto(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 2) throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
                return InstantaneDto(epoch: dco_decode_u_64(arr[0]),
membres: dco_decode_list_membre_dto(arr[1]),); }

@protected List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return (raw as List<dynamic>).map(dco_decode_list_prim_u_8_strict).toList(); }

@protected List<MembreDto> dco_decode_list_membre_dto(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return (raw as List<dynamic>).map(dco_decode_membre_dto).toList(); }

@protected List<int> dco_decode_list_prim_u_32_loose(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as List<int>; }

@protected Uint32List dco_decode_list_prim_u_32_strict(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as Uint32List; }

@protected List<int> dco_decode_list_prim_u_8_loose(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as List<int>; }

@protected Uint8List dco_decode_list_prim_u_8_strict(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as Uint8List; }

@protected MembreDto dco_decode_membre_dto(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 2) throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
                return MembreDto(leafIndex: dco_decode_u_32(arr[0]),
identity: dco_decode_String(arr[1]),); }

@protected Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw == null ? null : dco_decode_list_prim_u_8_strict(raw); }

@protected int dco_decode_u_32(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as int; }

@protected BigInt dco_decode_u_64(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return dcoDecodeU64(raw); }

@protected int dco_decode_u_8(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as int; }

@protected void dco_decode_unit(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return; }

@protected BigInt dco_decode_usize(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return dcoDecodeU64(raw); }

@protected AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_String(deserializer);
        return AnyhowException(inner); }

@protected Moteur sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return MoteurImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer)); }

@protected Moteur sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return MoteurImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer)); }

@protected Moteur sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return MoteurImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer)); }

@protected Moteur sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return MoteurImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer)); }

@protected String sse_decode_String(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_list_prim_u_8_strict(deserializer);
        return utf8.decoder.convert(inner); }

@protected bool sse_decode_bool(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint8() != 0; }

@protected InstantaneDto sse_decode_box_autoadd_instantane_dto(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return (sse_decode_instantane_dto(deserializer)); }

@protected CommitDto sse_decode_commit_dto(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_commit = sse_decode_list_prim_u_8_strict(deserializer);
var var_welcome = sse_decode_opt_list_prim_u_8_strict(deserializer);
var var_groupInfo = sse_decode_opt_list_prim_u_8_strict(deserializer);
return CommitDto(commit: var_commit, welcome: var_welcome, groupInfo: var_groupInfo); }

@protected EntrantDto sse_decode_entrant_dto(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

            var tag_ = sse_decode_i_32(deserializer);
            switch (tag_) { case 0: var var_clair = sse_decode_list_prim_u_8_strict(deserializer);
return EntrantDto_Application(clair: var_clair);case 1: var var_instantane = sse_decode_box_autoadd_instantane_dto(deserializer);
return EntrantDto_Commit(instantane: var_instantane);case 2: return EntrantDto_Proposition();case 3: return EntrantDto_Ignore(); default: throw UnimplementedError(''); }
             }

@protected InstantaneDto sse_decode_instantane_dto(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_epoch = sse_decode_u_64(deserializer);
var var_membres = sse_decode_list_membre_dto(deserializer);
return InstantaneDto(epoch: var_epoch, membres: var_membres); }

@protected List<Uint8List> sse_decode_list_list_prim_u_8_strict(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

        var len_ = sse_decode_i_32(deserializer);
        var ans_ = <Uint8List>[];
        for (var idx_ = 0; idx_ < len_; ++idx_) { ans_.add(sse_decode_list_prim_u_8_strict(deserializer)); }
        return ans_;
         }

@protected List<MembreDto> sse_decode_list_membre_dto(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

        var len_ = sse_decode_i_32(deserializer);
        var ans_ = <MembreDto>[];
        for (var idx_ = 0; idx_ < len_; ++idx_) { ans_.add(sse_decode_membre_dto(deserializer)); }
        return ans_;
         }

@protected List<int> sse_decode_list_prim_u_32_loose(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var len_ = sse_decode_i_32(deserializer);
                return deserializer.buffer.getUint32List(len_); }

@protected Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var len_ = sse_decode_i_32(deserializer);
                return deserializer.buffer.getUint32List(len_); }

@protected List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var len_ = sse_decode_i_32(deserializer);
                return deserializer.buffer.getUint8List(len_); }

@protected Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var len_ = sse_decode_i_32(deserializer);
                return deserializer.buffer.getUint8List(len_); }

@protected MembreDto sse_decode_membre_dto(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_leafIndex = sse_decode_u_32(deserializer);
var var_identity = sse_decode_String(deserializer);
return MembreDto(leafIndex: var_leafIndex, identity: var_identity); }

@protected Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

            if (sse_decode_bool(deserializer)) {
                return (sse_decode_list_prim_u_8_strict(deserializer));
            } else {
                return null;
            }
             }

@protected int sse_decode_u_32(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint32(); }

@protected BigInt sse_decode_u_64(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getBigUint64(); }

@protected int sse_decode_u_8(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint8(); }

@protected void sse_decode_unit(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
 }

@protected BigInt sse_decode_usize(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getBigUint64(); }

@protected int sse_decode_i_32(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getInt32(); }

@protected void sse_encode_AnyhowException(AnyhowException self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.message, serializer); }

@protected void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(Moteur self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_usize((self as MoteurImpl).frbInternalSseEncode(move: true), serializer); }

@protected void sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(Moteur self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_usize((self as MoteurImpl).frbInternalSseEncode(move: false), serializer); }

@protected void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(Moteur self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_usize((self as MoteurImpl).frbInternalSseEncode(move: false), serializer); }

@protected void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMoteur(Moteur self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_usize((self as MoteurImpl).frbInternalSseEncode(move: null), serializer); }

@protected void sse_encode_String(String self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer); }

@protected void sse_encode_bool(bool self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint8(self ? 1 : 0); }

@protected void sse_encode_box_autoadd_instantane_dto(InstantaneDto self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_instantane_dto(self, serializer); }

@protected void sse_encode_commit_dto(CommitDto self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_list_prim_u_8_strict(self.commit, serializer);
sse_encode_opt_list_prim_u_8_strict(self.welcome, serializer);
sse_encode_opt_list_prim_u_8_strict(self.groupInfo, serializer);
 }

@protected void sse_encode_entrant_dto(EntrantDto self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
switch (self) { case EntrantDto_Application(clair: final clair): sse_encode_i_32(0, serializer); sse_encode_list_prim_u_8_strict(clair, serializer);
case EntrantDto_Commit(instantane: final instantane): sse_encode_i_32(1, serializer); sse_encode_box_autoadd_instantane_dto(instantane, serializer);
case EntrantDto_Proposition(): sse_encode_i_32(2, serializer); case EntrantDto_Ignore(): sse_encode_i_32(3, serializer);   } }

@protected void sse_encode_instantane_dto(InstantaneDto self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_u_64(self.epoch, serializer);
sse_encode_list_membre_dto(self.membres, serializer);
 }

@protected void sse_encode_list_list_prim_u_8_strict(List<Uint8List> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
        for (final item in self) { sse_encode_list_prim_u_8_strict(item, serializer); } }

@protected void sse_encode_list_membre_dto(List<MembreDto> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
        for (final item in self) { sse_encode_membre_dto(item, serializer); } }

@protected void sse_encode_list_prim_u_32_loose(List<int> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
                    serializer.buffer.putUint32List(self is Uint32List ? self : Uint32List.fromList(self)); }

@protected void sse_encode_list_prim_u_32_strict(Uint32List self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
                    serializer.buffer.putUint32List(self); }

@protected void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
                    serializer.buffer.putUint8List(self is Uint8List ? self : Uint8List.fromList(self)); }

@protected void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
                    serializer.buffer.putUint8List(self); }

@protected void sse_encode_membre_dto(MembreDto self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_u_32(self.leafIndex, serializer);
sse_encode_String(self.identity, serializer);
 }

@protected void sse_encode_opt_list_prim_u_8_strict(Uint8List? self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs

                sse_encode_bool(self != null, serializer);
                if (self != null) {
                    sse_encode_list_prim_u_8_strict(self, serializer);
                }
                 }

@protected void sse_encode_u_32(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint32(self); }

@protected void sse_encode_u_64(BigInt self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putBigUint64(self); }

@protected void sse_encode_u_8(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint8(self); }

@protected void sse_encode_unit(void self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
 }

@protected void sse_encode_usize(BigInt self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putBigUint64(self); }

@protected void sse_encode_i_32(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putInt32(self); }
                }
                

            @sealed class MoteurImpl extends RustOpaque implements Moteur {
                // Not to be used by end users
                MoteurImpl.frbInternalDcoDecode(List<dynamic> wire):
                    super.frbInternalDcoDecode(wire, _kStaticData);

                // Not to be used by end users
                MoteurImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative):
                    super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

                static final _kStaticData = RustArcStaticData(
                    rustArcIncrementStrongCount: RustLib.instance.api.rust_arc_increment_strong_count_Moteur,
                    rustArcDecrementStrongCount: RustLib.instance.api.rust_arc_decrement_strong_count_Moteur,
                    rustArcDecrementStrongCountPtr: RustLib.instance.api.rust_arc_decrement_strong_count_MoteurPtr,
                );

                 Future<CommitDto>  ajouterMembres({required String conversationId , required List<Uint8List> keyPackages , required List<int> aad })=>RustLib.instance.api.crateApiMlsMoteurAjouterMembres(that: this, conversationId: conversationId, keyPackages: keyPackages, aad: aad);


 Future<Uint8List>  chiffrer({required String conversationId , required List<int> clair , required List<int> aad })=>RustLib.instance.api.crateApiMlsMoteurChiffrer(that: this, conversationId: conversationId, clair: clair, aad: aad);


/// Clé publique de signature de l'appareil (à publier dans `mls_devices`).
 Uint8List  cleSignaturePublique()=>RustLib.instance.api.crateApiMlsMoteurCleSignaturePublique(that: this, );


/// Credential MLS sérialisée de l'appareil (à publier dans `mls_devices`).
 Uint8List  credential()=>RustLib.instance.api.crateApiMlsMoteurCredential(that: this, );


 Future<InstantaneDto>  creerGroupe({required String conversationId })=>RustLib.instance.api.crateApiMlsMoteurCreerGroupe(that: this, conversationId: conversationId);


 Future<List<Uint8List>>  creerKeyPackages({required int n , required bool dernierRecours })=>RustLib.instance.api.crateApiMlsMoteurCreerKeyPackages(that: this, n: n, dernierRecours: dernierRecours);


 Future<Uint8List>  exporterGroupInfo({required String conversationId })=>RustLib.instance.api.crateApiMlsMoteurExporterGroupInfo(that: this, conversationId: conversationId);


 Future<InstantaneDto>  fusionnerCommitEnAttente({required String conversationId })=>RustLib.instance.api.crateApiMlsMoteurFusionnerCommitEnAttente(that: this, conversationId: conversationId);


 String  identite()=>RustLib.instance.api.crateApiMlsMoteurIdentite(that: this, );


 Future<InstantaneDto>  instantane({required String conversationId })=>RustLib.instance.api.crateApiMlsMoteurInstantane(that: this, conversationId: conversationId);


 Future<void>  jeterCommitEnAttente({required String conversationId })=>RustLib.instance.api.crateApiMlsMoteurJeterCommitEnAttente(that: this, conversationId: conversationId);


 Future<CommitDto>  rejoindreParCommitExterne({required String conversationId , required List<int> groupInfo , required List<int> aad })=>RustLib.instance.api.crateApiMlsMoteurRejoindreParCommitExterne(that: this, conversationId: conversationId, groupInfo: groupInfo, aad: aad);


 Future<CommitDto>  retirerMembres({required String conversationId , required List<int> leafIndices , required List<int> aad })=>RustLib.instance.api.crateApiMlsMoteurRetirerMembres(that: this, conversationId: conversationId, leafIndices: leafIndices, aad: aad);


 Future<EntrantDto>  traiterEntrant({required String conversationId , required List<int> message , required List<int> aadAttendu })=>RustLib.instance.api.crateApiMlsMoteurTraiterEntrant(that: this, conversationId: conversationId, message: message, aadAttendu: aadAttendu);


 Future<InstantaneDto>  traiterWelcome({required String conversationId , required List<int> welcome })=>RustLib.instance.api.crateApiMlsMoteurTraiterWelcome(that: this, conversationId: conversationId, welcome: welcome);


            }