import 'package:diaspo_niger/core/theme/admin_colors.dart';
import 'package:diaspo_niger/shared/widgets/app_icon.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../embassies/data/models/embassy_model.dart';
import '../../../embassies/data/datasources/embassy_remote_datasource.dart';

class AdminCreateEmbassyScreen extends ConsumerStatefulWidget {
  const AdminCreateEmbassyScreen({super.key});

  @override
  ConsumerState<AdminCreateEmbassyScreen> createState() =>
      _AdminCreateEmbassyScreenState();
}

class _AdminCreateEmbassyScreenState
    extends ConsumerState<AdminCreateEmbassyScreen> {
  final _formKey = GlobalKey<FormState>();
  bool _isLoading = false;

  // Form controllers
  final _nameController = TextEditingController();
  final _countryController = TextEditingController();
  final _cityController = TextEditingController();
  final _addressController = TextEditingController();
  final _phoneController = TextEditingController();
  final _emailController = TextEditingController();
  final _websiteController = TextEditingController();
  final _latitudeController = TextEditingController();
  final _longitudeController = TextEditingController();

  String _selectedType = 'embassy';
  final List<String> _selectedServices = [];
  final Map<String, String> _openingHours = {};
  final List<String> _jurisdictionCountries = [];
  final TextEditingController _jurisdictionController = TextEditingController();

  // Common Niger embassy services
  static const List<String> _availableServices = [
    'Passeports',
    'Visas',
    'État civil',
    'Légalisation de documents',
    'Carte consulaire',
    'Assistance aux ressortissants',
    'Bourses d\'études',
    'Affaires sociales',
    'Attestations diverses',
    'Procurations',
    'Laissez-passer',
    'Inscription consulaire',
  ];

  static const List<String> _embassyTypes = [
    'embassy',
    'consulate',
    'mission',
    'delegation',
  ];

  static const List<String> _weekDays = [
    'Lundi',
    'Mardi',
    'Mercredi',
    'Jeudi',
    'Vendredi',
    'Samedi',
    'Dimanche',
  ];

  @override
  void dispose() {
    _nameController.dispose();
    _countryController.dispose();
    _cityController.dispose();
    _addressController.dispose();
    _phoneController.dispose();
    _emailController.dispose();
    _websiteController.dispose();
    _latitudeController.dispose();
    _longitudeController.dispose();
    _jurisdictionController.dispose();
    super.dispose();
  }

  String _getTypeLabel(String type) {
    switch (type) {
      case 'embassy':
        return 'Ambassade';
      case 'consulate':
        return 'Consulat';
      case 'mission':
        return 'Mission diplomatique';
      case 'delegation':
        return 'Délégation';
      default:
        return type;
    }
  }

  Future<void> _submitForm() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isLoading = true);

    try {
      final embassy = EmbassyModel(
        id: '', // Will be generated by Firestore
        name: _nameController.text.trim(),
        country: _countryController.text.trim(),
        city: _cityController.text.trim(),
        address: _addressController.text.trim(),
        phone:
            _phoneController.text.trim().isEmpty
                ? null
                : _phoneController.text.trim(),
        email:
            _emailController.text.trim().isEmpty
                ? null
                : _emailController.text.trim(),
        website:
            _websiteController.text.trim().isEmpty
                ? null
                : _websiteController.text.trim(),
        latitude: double.tryParse(_latitudeController.text),
        longitude: double.tryParse(_longitudeController.text),
        type: _selectedType,
        services: _selectedServices,
        openingHours: _openingHours,
        jurisdictionCountries: _jurisdictionCountries,
        isVerified: false, // Requires admin verification
        isSuspended: false,
      );

      final dataSource = EmbassyRemoteDataSourceImpl();
      await dataSource.createEmbassy(embassy);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Ambassade créée avec succès!'),
            backgroundColor: AdminColors.statusGreen,
          ),
        );
        context.pop();
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Erreur: $e'), backgroundColor: AdminColors.statusRed),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  void _addJurisdiction() {
    final country = _jurisdictionController.text.trim();
    if (country.isNotEmpty && !_jurisdictionCountries.contains(country)) {
      setState(() {
        _jurisdictionCountries.add(country);
        _jurisdictionController.clear();
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Scaffold(
      appBar: AppBar(
        title: const Text('Créer une ambassade'),
        backgroundColor: theme.colorScheme.surface,
      ),
      body: Form(
        key: _formKey,
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(24),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Help text
              Container(
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  color: AdminColors.actionBlue.withValues(alpha: 0.1),
                  borderRadius: BorderRadius.circular(12),
                  border: Border.all(
                      color: AdminColors.actionBlue.withValues(alpha: 0.3)),
                ),
                child: Row(
                  children: [
                    AppIcon(AppIcon.info, color: AdminColors.actionBlue),
                    const SizedBox(width: 12),
                    const Expanded(
                      child: Text(
                        'Remplissez ce formulaire pour créer une nouvelle ambassade. '
                        'La demande sera vérifiée avant publication.',
                        style: TextStyle(fontSize: 14),
                      ),
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 32),

              // Section: Informations de base
              _buildSectionHeader('Informations de base', Icon(Icons.business, color: Theme.of(context).primaryColor, size: 24)),
              const SizedBox(height: 16),

              // Type
              //
              // `isExpanded` n'est pas cosmétique ici : le champ replié
              // empile *tous* ses éléments dans un IndexedStack, y compris le
              // hintText que Flutter convertit en `hint`. Un IndexedStack se
              // dimensionne sur son plus grand enfant et non sur celui qui est
              // affiché, donc la largeur était dictée par « Sélectionnez le
              // type d'établissement » (invisible) au lieu d'« Ambassade » —
              // d'où le débordement de 54 px sur appareil. `isExpanded` place
              // cette pile dans un Expanded ; l'ellipse fait le reste.
              DropdownButtonFormField<String>(
                initialValue: _selectedType,
                isExpanded: true,
                decoration: _inputDecoration(
                  'Type *',
                  'Sélectionnez le type d\'établissement',
                ),
                hint: const Text(
                  'Sélectionnez le type d\'établissement',
                  maxLines: 1,
                  overflow: TextOverflow.ellipsis,
                ),
                items:
                    _embassyTypes.map((type) {
                      return DropdownMenuItem(
                        value: type,
                        child: Text(
                          _getTypeLabel(type),
                          maxLines: 1,
                          overflow: TextOverflow.ellipsis,
                        ),
                      );
                    }).toList(),
                onChanged: (value) {
                  if (value != null) {
                    setState(() => _selectedType = value);
                  }
                },
              ),
              const SizedBox(height: 16),

              // Name
              TextFormField(
                controller: _nameController,
                decoration: _inputDecoration(
                  'Nom *',
                  'Ex: Ambassade du Niger en France',
                ),
                validator: (value) {
                  if (value == null || value.trim().isEmpty) {
                    return 'Le nom est obligatoire';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 16),

              // Country
              TextFormField(
                controller: _countryController,
                decoration: _inputDecoration(
                  'Pays d\'implantation *',
                  'Ex: France',
                ),
                validator: (value) {
                  if (value == null || value.trim().isEmpty) {
                    return 'Le pays est obligatoire';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 16),

              // City
              TextFormField(
                controller: _cityController,
                decoration: _inputDecoration('Ville *', 'Ex: Paris'),
                validator: (value) {
                  if (value == null || value.trim().isEmpty) {
                    return 'La ville est obligatoire';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 16),

              // Address
              TextFormField(
                controller: _addressController,
                decoration: _inputDecoration(
                  'Adresse complète *',
                  'Ex: 154 rue de Longchamp, 75116 Paris',
                ),
                maxLines: 2,
                validator: (value) {
                  if (value == null || value.trim().isEmpty) {
                    return 'L\'adresse est obligatoire';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 32),

              // Section: Contact
              _buildSectionHeader('Contact', AppIcon(AppIcon.call, color: Theme.of(context).primaryColor, size: 24)),
              const SizedBox(height: 16),

              TextFormField(
                controller: _phoneController,
                decoration: _inputDecoration(
                  'Téléphone',
                  'Ex: +33 1 45 04 80 60',
                ),
                keyboardType: TextInputType.phone,
              ),
              const SizedBox(height: 16),

              TextFormField(
                controller: _emailController,
                decoration: _inputDecoration(
                  'Email',
                  'Ex: contact@ambassade-niger.fr',
                ),
                keyboardType: TextInputType.emailAddress,
                validator: (value) {
                  if (value != null && value.isNotEmpty) {
                    if (!RegExp(
                      r'^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$',
                    ).hasMatch(value)) {
                      return 'Email invalide';
                    }
                  }
                  return null;
                },
              ),
              const SizedBox(height: 16),

              TextFormField(
                controller: _websiteController,
                decoration: _inputDecoration(
                  'Site web',
                  'Ex: https://www.ambassade-niger.fr',
                ),
                keyboardType: TextInputType.url,
              ),
              const SizedBox(height: 32),

              // Section: Localisation
              _buildSectionHeader('Localisation GPS (optionnel)', Icon(Icons.map, color: Theme.of(context).primaryColor, size: 24)),
              const SizedBox(height: 16),

              Row(
                children: [
                  Expanded(
                    child: TextFormField(
                      controller: _latitudeController,
                      decoration: _inputDecoration('Latitude', 'Ex: 48.8566'),
                      keyboardType: const TextInputType.numberWithOptions(
                        decimal: true,
                      ),
                    ),
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                    child: TextFormField(
                      controller: _longitudeController,
                      decoration: _inputDecoration('Longitude', 'Ex: 2.3522'),
                      keyboardType: const TextInputType.numberWithOptions(
                        decimal: true,
                      ),
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 32),

              // Section: Services
              _buildSectionHeader('Services proposés', Icon(Icons.room_service, color: Theme.of(context).primaryColor, size: 24)),
              const SizedBox(height: 16),

              Wrap(
                spacing: 8,
                runSpacing: 8,
                children:
                    _availableServices.map((service) {
                      final isSelected = _selectedServices.contains(service);
                      return FilterChip(
                        label: Text(service),
                        selected: isSelected,
                        onSelected: (selected) {
                          setState(() {
                            if (selected) {
                              _selectedServices.add(service);
                            } else {
                              _selectedServices.remove(service);
                            }
                          });
                        },
                      );
                    }).toList(),
              ),
              const SizedBox(height: 32),

              // Section: Jurisdiction
              _buildSectionHeader('Pays sous juridiction', AppIcon(AppIcon.public, color: Theme.of(context).primaryColor, size: 24)),
              const SizedBox(height: 8),
              Text(
                'Indiquez les pays dont les ressortissants peuvent contacter cette ambassade.',
                style: TextStyle(color: AdminColors.text2, fontSize: 13),
              ),
              const SizedBox(height: 16),

              Row(
                children: [
                  Expanded(
                    child: TextFormField(
                      controller: _jurisdictionController,
                      decoration: _inputDecoration(
                        'Ajouter un pays',
                        'Ex: Niger',
                      ),
                      onFieldSubmitted: (_) => _addJurisdiction(),
                    ),
                  ),
                  const SizedBox(width: 8),
                  IconButton(
                    onPressed: _addJurisdiction,
                    icon: const Icon(Icons.add_circle),
                    color: theme.primaryColor,
                  ),
                ],
              ),
              const SizedBox(height: 12),

              Wrap(
                spacing: 8,
                runSpacing: 8,
                children:
                    _jurisdictionCountries.map((country) {
                      return Chip(
                        label: Text(country),
                        deleteIcon: const AppIcon(AppIcon.close, size: 18),
                        onDeleted: () {
                          setState(() {
                            _jurisdictionCountries.remove(country);
                          });
                        },
                      );
                    }).toList(),
              ),
              const SizedBox(height: 32),

              // Section: Opening Hours
              _buildSectionHeader('Horaires d\'ouverture', Icon(Icons.schedule, color: Theme.of(context).primaryColor, size: 24)),
              const SizedBox(height: 16),

              ..._weekDays.map((day) {
                return Padding(
                  padding: const EdgeInsets.only(bottom: 12),
                  child: Row(
                    children: [
                      SizedBox(
                        width: 100,
                        child: Text(
                          day,
                          style: const TextStyle(fontWeight: FontWeight.w500),
                        ),
                      ),
                      Expanded(
                        child: TextFormField(
                          decoration: _inputDecoration(
                            '',
                            'Ex: 09:00 - 17:00 ou Fermé',
                          ),
                          onChanged: (value) {
                            if (value.isNotEmpty) {
                              _openingHours[day] = value;
                            } else {
                              _openingHours.remove(day);
                            }
                          },
                        ),
                      ),
                    ],
                  ),
                );
              }),
              const SizedBox(height: 40),

              // Submit button
              SizedBox(
                width: double.infinity,
                height: 54,
                child: ElevatedButton(
                  onPressed: _isLoading ? null : _submitForm,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: theme.primaryColor,
                    foregroundColor: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                  child:
                      _isLoading
                          ? const SizedBox(
                            width: 24,
                            height: 24,
                            child: CircularProgressIndicator(
                              color: Colors.white,
                              strokeWidth: 2,
                            ),
                          )
                          : const Text(
                            'Créer l\'ambassade',
                            style: TextStyle(
                              fontSize: 16,
                              fontWeight: FontWeight.bold,
                            ),
                          ),
                ),
              ),
              const SizedBox(height: 32),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildSectionHeader(String title, Widget icon) {
    return Row(
      children: [
        icon,
        const SizedBox(width: 8),
        // Expanded : les titres longs (« Localisation GPS (optionnel) »)
        // passent à la ligne aux grandes échelles de police au lieu de
        // déborder de la Row.
        Expanded(
          child: Text(
            title,
            style: Theme.of(
              context,
            ).textTheme.titleMedium?.copyWith(fontWeight: FontWeight.bold),
          ),
        ),
      ],
    );
  }

  InputDecoration _inputDecoration(String label, String hint) {
    return InputDecoration(
      labelText: label.isEmpty ? null : label,
      hintText: hint,
      border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
      contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
    );
  }
}
