// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfaTQD-3li5WdUc-3t6f7AYSD4ts7M6d0',
    appId: '1:539228418594:web:3b01752fce9a0e328e507b',
    messagingSenderId: '539228418594',
    projectId: 'diaspo-niger',
    authDomain: 'diaspo-niger.firebaseapp.com',
    storageBucket: 'diaspo-niger.firebasestorage.app',
    measurementId: 'G-P6W4Z32N2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJsOIAjUkFJ1LJybkfwknw5xaNSdZbh0E',
    appId: '1:539228418594:android:64adecd6aa5e20368e507b',
    messagingSenderId: '539228418594',
    projectId: 'diaspo-niger',
    storageBucket: 'diaspo-niger.firebasestorage.app',
    databaseURL:
        'https://diaspo-niger-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOna4SC-OwrF_Xqms5eoNvp5MqHW1Cf_M',
    appId: '1:539228418594:ios:6cdc9491c795c4a38e507b',
    messagingSenderId: '539228418594',
    projectId: 'diaspo-niger',
    storageBucket: 'diaspo-niger.firebasestorage.app',
    iosClientId:
        '539228418594-t57j3s9ncgldbgk49a1td9f1hdrld7ic.apps.googleusercontent.com',
    iosBundleId: 'com.diasponiger.diaspoNiger',
    databaseURL:
        'https://diaspo-niger-default-rtdb.europe-west1.firebasedatabase.app',
  );
}
