// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'mls.freezed.dart';

            // These functions are ignored because they are not marked as `pub`: `code`, `commit`, `instantane`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`


            

            
                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Moteur>>
                abstract class Moteur implements RustOpaqueInterface {
                     Future<CommitDto>  ajouterMembres({required String conversationId , required List<Uint8List> keyPackages , required List<int> aad });


 Future<Uint8List>  chiffrer({required String conversationId , required List<int> clair , required List<int> aad });


/// Clé publique de signature de l'appareil (à publier dans `mls_devices`).
 Uint8List  cleSignaturePublique();


/// Credential MLS sérialisée de l'appareil (à publier dans `mls_devices`).
 Uint8List  credential();


 Future<InstantaneDto>  creerGroupe({required String conversationId });


 Future<List<Uint8List>>  creerKeyPackages({required int n , required bool dernierRecours });


 Future<Uint8List>  exporterGroupInfo({required String conversationId });


 Future<InstantaneDto>  fusionnerCommitEnAttente({required String conversationId });


 String  identite();


 Future<InstantaneDto>  instantane({required String conversationId });


 Future<void>  jeterCommitEnAttente({required String conversationId });


/// Supprime l'état local d'un groupe (perdant de la course à la création).
 Future<void>  oublierGroupe({required String conversationId });


/// Ouvre (ou crée) la base SQLite du moteur pour cet appareil.
static Future<Moteur>  ouvrir({required String dbPath , required String userId , required String deviceId })=>RustLib.instance.api.crateApiMlsMoteurOuvrir(dbPath: dbPath, userId: userId, deviceId: deviceId);


 Future<CommitDto>  rejoindreParCommitExterne({required String conversationId , required List<int> groupInfo , required List<int> aad });


 Future<CommitDto>  retirerMembres({required String conversationId , required List<int> leafIndices , required List<int> aad });


 Future<EntrantDto>  traiterEntrant({required String conversationId , required List<int> message , required List<int> aadAttendu });


 Future<InstantaneDto>  traiterWelcome({required String conversationId , required List<int> welcome });



                    
                }
                

class CommitDto  {
                final Uint8List commit;
final Uint8List? welcome;
final Uint8List? groupInfo;

                const CommitDto({required this.commit ,this.welcome ,this.groupInfo ,});





        @override
        int get hashCode => commit.hashCode^welcome.hashCode^groupInfo.hashCode;



        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is CommitDto &&
                runtimeType == other.runtimeType
                && commit == other.commit&& welcome == other.welcome&& groupInfo == other.groupInfo;

            }

@freezed
                sealed class EntrantDto with _$EntrantDto  {
                    const EntrantDto._();

                     const factory EntrantDto.application({   required Uint8List clair , }) = EntrantDto_Application;
 const factory EntrantDto.commit({   required InstantaneDto instantane , }) = EntrantDto_Commit;
 const factory EntrantDto.proposition() = EntrantDto_Proposition;
 const factory EntrantDto.ignore() = EntrantDto_Ignore;

                    

                    
                }

class InstantaneDto  {
                final BigInt epoch;
final List<MembreDto> membres;

                const InstantaneDto({required this.epoch ,required this.membres ,});





        @override
        int get hashCode => epoch.hashCode^membres.hashCode;



        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is InstantaneDto &&
                runtimeType == other.runtimeType
                && epoch == other.epoch&& membres == other.membres;

            }

class MembreDto  {
                final int leafIndex;
final String identity;

                const MembreDto({required this.leafIndex ,required this.identity ,});





        @override
        int get hashCode => leafIndex.hashCode^identity.hashCode;



        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is MembreDto &&
                runtimeType == other.runtimeType
                && leafIndex == other.leafIndex&& identity == other.identity;

            }
            